version: '3.7'

services:
  api-tests:
    image: "api-tests-image"
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    command: /bin/sh -c "pytest -sv --alluredir=allure-results"
    working_dir: /app
    environment:
      PREPROD_URL: ${url}
      API_AUTH: ${auth}
      PROJECT_ID: ${project}
      REGION_ID: ${region}
      USERNAME_PREPROD: ${username}
      PASSWORD: ${password}

#  allure-report:
#    image: "api-tests-image"
#    volumes:
#      - ./:/app
#    command: /bin/sh -c "allure generate allure-results --clean -o allure-report"
#    working_dir: /app