version: '3.7'

services:
  api-tests:
    image: "api-tests-image"
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    command: /bin/sh -c "pytest -sv --alluredir=allure-results"
    working_dir: /app
    environment:
      PREPROD_URL: ${PREPROD_URL}
      API_AUTH: ${API_AUTH}
      PROJECT_ID: ${PROJECT_ID}
      REGION_ID: ${REGION_ID}
      USERNAME_PREPROD: ${USERNAME_PREPROD}
      PASSWORD: ${PASSWORD}

  allure-report:
    image: "api-tests-image"
    volumes:
      - ./:/app
    command: /bin/sh -c "allure generate allure-results --clean -o allure-report"
    working_dir: /app