name: API Tests

on: [push]

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

#      - name: Checkout (copy) gh-pages repository to GitHub runner
#        uses: actions/checkout@v4
#        with:
#          ref: gh-pages
#          path: ./.github/gh-pages

      - name: Run api-tests via docker-compose
        env:
          PREPROD_URL: ${{ secrets.PREPROD_URL }}
          API_AUTH: ${{ secrets.API_AUTH }}
          PROJECT_ID: ${{ secrets.PROJECT_ID }}
          REGION_ID: ${{ secrets.REGION_ID }}
          USERNAME_PREPROD: ${{ secrets.USERNAME_PREPROD }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: docker-compose up
#        docker-compose up --exit-code-from api-tests || true

#  allure-report:
#    runs-on: ubuntu-latest
#    needs: run-tests
#    steps:
#      - name: Generate Allure report
#        run: |
#          docker-compose up allure-report


#          sudo docker-compose run api-tests /bin/sh -c "allure generate allure-results --clean -o allure-report"

#      - name: Copy history from gh-pages to allure-results
#        run: |
#          sudo mkdir -p allure-results/history
#          sudo cp -R ./.github/gh-pages/history/* allure-results/history/

#      - name: Generate Allure report
#        run: |
#          sudo docker-compose run api-tests /bin/sh -c "allure generate allure-results --clean -o allure-report"

#      - name: Update Allure history
#        run: |
#          sudo cp -R allure-report/history/* ./.github/gh-pages/history/

#      - name: Deploy to GitHub Pages
#        uses: JamesIves/github-pages-deploy-action@4.1.5
#        with:
#          token: ${{ secrets.CI_TOKEN }}
#          branch: gh-pages
#          folder: allure-report
#          clean: true